//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Reg_Login_Page.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.InteropServices;
    using System.Web.Mvc;
    using MVC_Reg_Login_Page.CommonFile;

    public partial class Registration
    {
        public int UserID { get; set; }

        [DisplayName("First Name")]
       
        public string FirstName { get; set; }

        [StringLength(20,MinimumLength = 5,ErrorMessage="Length between 5 to 20")]
        public string LastName { get; set; }
        [Range(14,65,ErrorMessage ="Should be Between 14 and 65")]
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }

        //public List<SelectListItem> CityList { get; set; }
       // [RegularExpression("^\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*$", ErrorMessage ="Please Enter Valid Email")]
        public string email { get; set; }
        [Required]
        public string Password { get; set; }

        [DisplayFormat(ApplyFormatInEditMode =true, DataFormatString ="{0:d}")]
        [CurrentDate(ErrorMessage ="Write Today Date")]
        public DateTime TodayDate { get; set; }
    }
}
